version: 0.2

env:
  # variables:
  #   JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
  parameter-store:
    AWS_ACCESS_KEY_ID: "terraform-key-id"
    AWS_SECRET_ACCESS_KEY: "terraform-access-key"

phases:
  install:
    commands:
      - echo Entered the Terraform install phase...
      - yum -y install sudo
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - ls
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the Terraform plan phase...
      - export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
      - export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
      - terraform init
      - terraform plan -out myplan
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the Terraform apply phase...
      - echo Build started on `date`
      - ls
      - cat .terraform.lock.hcl
      - terraform apply -auto-approve myplan
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

# reports:
#   my-project-1-my-report-group:
#     files:
#       - "**/*"
#     base-directory: 'target/tests/reports'
#     discard-paths: no
#   reportGroupCucumberJson:
#     files:
#       - 'cucumber/target/cucumber-tests.xml'
#     discard-paths: yes
#     file-format: CUCUMBERJSON # default is JUNITXML
# artifacts:
#   files:
#     - target/messageUtil-1.0.jar
#   discard-paths: yes
#   secondary-artifacts:
#     artifact1:
#       files:
#         - target/artifact-1.0.jar
#       discard-paths: yes
#     artifact2:
#       files:
#         - target/artifact-2.0.jar
#       discard-paths: yes
# cache:
#   paths:
#     - '/root/.m2/**/*'
